// <auto-generated />
using System;
using GioChuanGiangDay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GioChuanGiangDay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503101110_AddDangHocNghienCuuSinhToGiangVien")]
    partial class AddDangHocNghienCuuSinhToGiangVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GioChuanGiangDay.Models.DmGioChuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GioChuanGiangDay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GioChuanNckh")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LaTapSu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaChucDanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamApDung")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DmGioChuans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GioChuanGiangDay = 200m,
                            GioChuanNckh = 250m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_I",
                            NamApDung = "2025-2026",
                            TrinhDo = "TIEN_SI"
                        },
                        new
                        {
                            Id = 2,
                            GioChuanGiangDay = 240m,
                            GioChuanNckh = 210m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_II",
                            NamApDung = "2025-2026",
                            TrinhDo = "TIEN_SI"
                        },
                        new
                        {
                            Id = 3,
                            GioChuanGiangDay = 280m,
                            GioChuanNckh = 170m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_III",
                            NamApDung = "2025-2026",
                            TrinhDo = "TIEN_SI"
                        },
                        new
                        {
                            Id = 4,
                            GioChuanGiangDay = 300m,
                            GioChuanNckh = 150m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_III",
                            NamApDung = "2025-2026",
                            TrinhDo = "THAC_SI"
                        },
                        new
                        {
                            Id = 5,
                            GioChuanGiangDay = 100m,
                            GioChuanNckh = 50m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_III",
                            NamApDung = "2025-2026",
                            TrinhDo = "KHAC"
                        },
                        new
                        {
                            Id = 6,
                            GioChuanGiangDay = 80m,
                            GioChuanNckh = 40m,
                            LaTapSu = false,
                            MaChucDanh = "TRO_GIANG",
                            NamApDung = "2025-2026",
                            TrinhDo = "THAC_SI"
                        });
                });

            modelBuilder.Entity("GioChuanGiangDay.Models.DmHeSoSiSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HeSo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SiSoDen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiSoTu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DmHeSoSiSos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GhiChu = "Dưới hoặc bằng 40 sinh viên",
                            HeSo = 1.0m,
                            SiSoDen = 40,
                            SiSoTu = 0
                        },
                        new
                        {
                            Id = 2,
                            GhiChu = "Từ 41 đến 50 sinh viên",
                            HeSo = 1.1m,
                            SiSoDen = 50,
                            SiSoTu = 41
                        },
                        new
                        {
                            Id = 3,
                            GhiChu = "Từ 51 đến 60 sinh viên",
                            HeSo = 1.2m,
                            SiSoDen = 60,
                            SiSoTu = 51
                        },
                        new
                        {
                            Id = 4,
                            GhiChu = "Từ 61 đến 70 sinh viên",
                            HeSo = 1.3m,
                            SiSoDen = 70,
                            SiSoTu = 61
                        },
                        new
                        {
                            Id = 5,
                            GhiChu = "Từ 71 đến 80 sinh viên",
                            HeSo = 1.4m,
                            SiSoDen = 80,
                            SiSoTu = 71
                        },
                        new
                        {
                            Id = 6,
                            GhiChu = "Từ 81 sinh viên trở lên",
                            HeSo = 1.5m,
                            SiSoTu = 81
                        });
                });

            modelBuilder.Entity("GioChuanGiangDay.Models.DmHoatDongQuyDoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanMinhChung")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanTyLeDongGop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GioQuyDoiMacDinh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HeSoMacDinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaHoatDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NhomHoatDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHoatDong")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DmHoatDongQuyDois");
                });

            modelBuilder.Entity("GioChuanGiangDay.Models.GiangDayChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GioQuyDoiLyThuyet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GioQuyDoiThucHanh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HeSoSiSo")
                        .HasColumnType("TEXT");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LopHocPhan")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaHocPhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiSo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SoTietLyThuyet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTietThucHanh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTinChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongGioQuyDoi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.ToTable("GiangDayChiTiets");
                });

            modelBuilder.Entity("GioChuanGiangDay.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoMon")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DangHocNghienCuuSinh")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangLamViec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Khoa")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LaTapSu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaChucDanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("GioChuanGiangDay.Models.HoatDongQuyDoiChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DmHoatDongQuyDoiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileMinhChung")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GioDuocTinh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GioQuyDoiMacDinh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HeSo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TyLeDongGop")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DmHoatDongQuyDoiId");

                    b.HasIndex("GiangVienId");

                    b.ToTable("HoatDongQuyDoiChiTiets");
                });

            modelBuilder.Entity("GioChuanGiangDay.Models.GiangDayChiTiet", b =>
                {
                    b.HasOne("GioChuanGiangDay.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("GioChuanGiangDay.Models.HoatDongQuyDoiChiTiet", b =>
                {
                    b.HasOne("GioChuanGiangDay.Models.DmHoatDongQuyDoi", "DmHoatDongQuyDoi")
                        .WithMany()
                        .HasForeignKey("DmHoatDongQuyDoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GioChuanGiangDay.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DmHoatDongQuyDoi");

                    b.Navigation("GiangVien");
                });
#pragma warning restore 612, 618
        }
    }
}
