// <auto-generated />
using GioChuanGiangDay.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GioChuanGiangDay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502043436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GioChuanGiangDay.Models.DmGioChuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GioChuanGiangDay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GioChuanNckh")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LaTapSu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaChucDanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamApDung")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DmGioChuans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GioChuanGiangDay = 200m,
                            GioChuanNckh = 250m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_I",
                            NamApDung = "2025-2026",
                            TrinhDo = "TIEN_SI"
                        },
                        new
                        {
                            Id = 2,
                            GioChuanGiangDay = 240m,
                            GioChuanNckh = 210m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_II",
                            NamApDung = "2025-2026",
                            TrinhDo = "TIEN_SI"
                        },
                        new
                        {
                            Id = 3,
                            GioChuanGiangDay = 280m,
                            GioChuanNckh = 170m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_III",
                            NamApDung = "2025-2026",
                            TrinhDo = "TIEN_SI"
                        },
                        new
                        {
                            Id = 4,
                            GioChuanGiangDay = 300m,
                            GioChuanNckh = 150m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_III",
                            NamApDung = "2025-2026",
                            TrinhDo = "THAC_SI"
                        },
                        new
                        {
                            Id = 5,
                            GioChuanGiangDay = 100m,
                            GioChuanNckh = 50m,
                            LaTapSu = false,
                            MaChucDanh = "GV_HANG_III",
                            NamApDung = "2025-2026",
                            TrinhDo = "KHAC"
                        },
                        new
                        {
                            Id = 6,
                            GioChuanGiangDay = 80m,
                            GioChuanNckh = 40m,
                            LaTapSu = false,
                            MaChucDanh = "TRO_GIANG",
                            NamApDung = "2025-2026",
                            TrinhDo = "THAC_SI"
                        });
                });

            modelBuilder.Entity("GioChuanGiangDay.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoMon")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DangLamViec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Khoa")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LaTapSu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaChucDanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GiangViens");
                });
#pragma warning restore 612, 618
        }
    }
}
